version: "3.8"
services:
  sns-redis:
    container_name: sns-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: tlqkrus012345/sns-redis
    ports:
      - "6379:6379"
  sns-zookeeper:
    container_name: sns-zookeeper
    build:
      dockerfile: Dockerfile
      context: ./zookeeper
    image: tlqkrus012345/sns-zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  sns-kafka:
    container_name: sns-kafka
    build:
      dockerfile: Dockerfile
      context: ./kafka
    image: tlqkrus012345/sns-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=sns-zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - broker.endpoint.version=2.8
    depends_on:
      - sns-zookeeper

