spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sns-service
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  redis:
    host: localhost
    port: 6379

jwt:
  secret:
  key: ${JWT_SECRET_KEY}
  token:
    expired-time-ms: 2592000000

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
